export const pages = [
  {
    name: "Home",
    position: [0, 25, -105],
    rotation: [0, 0, 0],
    imageUrl: "/icons/home-icon-v1.png",
    url: null,
    componentUrl: null,
    sub: null,
  },
  {
    name: "About Me",
    position: [-50, 25, -105],
    rotation: [0, Math.PI * 0.1, 0],
    imageUrl: "/icons/about-icon-v1.png",
    url: "/PageAboutMe",
    componentUrl: null,
  },
  // {
  //   name: "Read More",
  //   position: [2, 25, 180],
  //   rotation: [0, Math.PI * 0.5, 0],
  //   imageUrl: "/icons/about-icon-v1.png",
  //   url: "/PageAboutMe",
  //   componentUrl: null,
  // },
  {
    name: "Contact Me",
    position: [123, 25, -86],
    rotation: [0, -Math.PI * 0.5, 0],
    imageUrl: "/icons/contact-icon-v1.png",
    url: "/PageContactMe",
    componentUrl: "@/components/pageComponents/aboutMe/AboutMe",
    sub: null,
  },
  {
    name: "Projects",
    position: [-190, 25, 150],
    rotation: [0, -Math.PI * 1, 0],
    imageUrl: "/icons/portfolio-icon-v1.png",
    url: "/PageProjects",
    componentUrl: null,
    sub: [
      {
        name: "Project1",
        position: [-180, 25, 248],
        rotation: [0, Math.PI * 1, 0],
        imageUrl: "/icons/portfolio-icon-v1.png",
        url: null,
        contentUrl: "/content-images/insta-v1.jpg",
        plate: {
          title: "Instagram Clone App",
          description: [
            "Built with Next.js and React.js, delivering a server-side rendered application for enhanced SEO and better performance.",
            "Incorporated Firebase for backend services, including real-time database functionality and user authentication.",
            "Utilized Moment.js for handling and manipulating dates, ensuring proper time stamping on user posts and comments.",
            "Adopted Recoil for efficient state management across the application, facilitating seamless user experiences.",
            "Integrated TailwindCSS as a utility-first CSS framework, allowing for rapid UI development.",
            "Enabled features such as user authentication, photo posting, commenting on posts, and user info viewing, replicating key aspects of the original Instagram platform.",
            "Implemented Material-UI and Emotion for effective and responsive styling of the application.",
          ],
          frameWorks: [
            "Reactjs",
            "Nextjs",
            "Tailwind CSS",
            "Recoil",
            "next-auth",
            "Firebase",
          ],
          deployed: "Vercel",
          deployUrl: "https://nextjs-app-instagram.vercel.app/",
          githubUrl: "https://github.com/omidnoor/nextjs-app-instagram",
        },
      },
      {
        name: "Project2",
        position: [-248, 25, 218],
        rotation: [0, Math.PI * 0.5, 0],
        imageUrl:
          "https://products.ls.graphics/mesh-gradients/images/15.-Perfume_1-p-130x130q80.jpeg",
        url: null,
        contentUrl: "/content-images/metal-plate-scifi-utopai-v1.jpg",
        plate: {
          title: "Content Creator App Using OpenAI API",
          description: [
            "Developed a content generation application leveraging OpenAI's GPT-3 API.",
            "Users provide specific subjects and keywords for custom content creation.",
            "Application uses Stripe API to handle e-commerce functionality, allowing users to purchase tokens for content generation.",
            "Utilized MongoDB for robust data management, including storing user credentials and content history.",
            "Deployed application on Google Cloud to manage long-wait responses from the OpenAI API.",
            "Implemented Auth0 for secure user authentication and access control.",
            "Built an intuitive and user-friendly interface using Material-UI, enhancing the overall user experience.",
            "Incorporated features such as content archiving, allowing users to review their previously generated content.",
            "Managed API endpoints for seamless handling of tokens, user data, and OpenAI API connections.",
          ],
          frameWorks: [
            "Reactjs",
            "Nextjs",
            "Material-UI",
            "MongoDB",
            "Stripe",
            "Google Cloud",
            "Auth0",
          ],
          deployed: "Vercel",
          deployUrl: "https://nextjs-openai-app.uw.r.appspot.com/",
          githubUrl: "https://github.com/omidnoor/nextjs-openai-app",
        },
      },
      {
        name: "Project3",
        position: [-248, 25, 100],
        rotation: [0, Math.PI * 0.5, 0],
        imageUrl:
          "https://products.ls.graphics/mesh-gradients/images/06.-Wisteria-p-130x130q80.jpeg",
        url: null,
        contentUrl: "/content-images/portfoli-v4-project-showcase-2.jpg",
        plate: {
          title: "Portfolio",
          description: [
            "Developed using React.js, Next.js, Three.js, and React Fiber, showcasing the cutting edge of modern web development.",
            "Utilized MongoDB to create and manage a robust and flexible database for form submissions.",
            "Integrated server-side and client-side error handling to ensure a seamless user experience and data integrity.",
            "Established API endpoints to connect the client-side to the server-side and MongoDB.",
            "Developed procedural materials and 3D models using Blender, adding depth and interactivity to the website.",
            "Employed modular SCSS for styling, enhancing code reusability, maintainability, and facilitating a scalable design system across the entire project.",
            "Utilized the react-spring library for animating user interface elements, providing a more engaging and responsive user experience.",
            "Integrated CameraControls for smooth camera movements in 3D spaces, enhancing user navigation and interaction.",
            "Designed an intuitive 3D UI/UX, improving user engagement and usability.",
            "Incorporated an email transporter to receive emails directly from users, ensuring immediate and efficient communication.",
          ],
          frameWorks: [
            "React-Three-Fiber",
            "Nextjs",
            "Drei",
            "MongoDB",
            "Formik",
            "Blender",
            "React-Spring",
            "Zustand",
          ],
          deployed: "Vercel",
          deployUrl: "https://www.onext.dev/",
          githubUrl: "https://github.com/omidnoor/portfolio-v4",
        },
      },
      {
        name: "Project4",
        position: [-248, 25, -18],
        rotation: [0, Math.PI * 0.5, 0],
        imageUrl:
          "https://products.ls.graphics/mesh-gradients/images/06.-Wisteria-p-130x130q80.jpeg",
        url: null,
        contentUrl: "/content-images/chatgpt-clone-project-showcase-1.jpg",
        plate: {
          title: "ChatGPT Clone App Using OpenAI API",
          description: [
            "Built a ChatGPT clone using a combination of React.js and Next.js for a modern, performant, and scalable frontend.",
            "Leveraged MongoDB for data storage, allowing for flexible and robust data management, including user sessions and chat history.",
            "Utilized 'openai-edge-stream' package to establish a seamless connection with the OpenAI language model, facilitating real-time conversation with AI.",
            "Created API endpoints to interact with the OpenAI API, enabling the application to generate dynamic AI responses.",
            "Developed API endpoints for fetching and writing data from/to the MongoDB database, ensuring consistent and real-time data operations.",
            "Used 'react-markdown' package for rendering the AI's responses in markdown format, providing a richer chat interface.",
            "Implemented 'uuid' for generating unique identifiers, ensuring every chat session and user interaction is accurately tracked and managed.",
            "Structured application with server-side rendering using Next.js for better SEO performance and faster page load times.",
            "Included tailwindcss for streamlined typographic styles, contributing to consistent and elegant UI.",
          ],
          frameWorks: [
            "Reactjs",
            "Nextjs",
            "Auth0",
            "MongoDB",
            "Tailwind CSS",
            "React-Icons",
            "OpenAI API",
            "React-Markdown",
          ],
          deployed: "Vercel",
          deployUrl: "https://memoai-iota.vercel.app/",
          githubUrl: "https://github.com/omidnoor/nextjs-chatgpt-clone",
        },
      },
    ],
  },
];
